{% set name = "json-stream-rs-tokenizer" %}
{% set version = "0.4.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0ac9c053b11a1af9efcfecbbe4b0fd8a0216a39f27a7df9ed08eb51fb99b5e43

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - setuptools
    - wheel
    - setuptools-rust >=1,<2
    - pip
  run:
    - python

test:
  imports:
    - json_stream_rs_tokenizer
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A faster tokenizer for the json-stream Python library
  home: https://github.com/smheidrich/py-json-stream-rs-tokenizer
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - rxm7706
