{% set name = "json-stream-rs-tokenizer" %}
{% set version = "0.4.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8c947c72966cc9b0076e0967077defae18c49a0600974c2829d48264240e2f72

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-rust >=1,<2
    - pip
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - json_stream_rs_tokenizer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A faster tokenizer for the json-stream Python library
  home: https://github.com/smheidrich/py-json-stream-rs-tokenizer
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
